---
product_name: manageiq
repos:
  ref: master
  manageiq:
    url: https://github.com/ManageIQ/manageiq.git
    ref:
  manageiq_appliance:
    url: https://github.com/ManageIQ/manageiq-appliance.git
    ref:
  manageiq_ui_service:
    url: https://github.com/ManageIQ/manageiq-ui-service.git
    ref:
version:
release:
rpm:
  version: 21.0.0
  release: 0
  repo_name:
  org_name: manageiq
  product_summary: ManageIQ Management Engine
  product_url: https://github.com/ManageIQ/manageiq
  changelog:
npm_registry: https://npm.manageiq.org
rpm_repository:
  s3_api:
    access_key:
    secret_key:
    bucket: rpm-manageiq-org
    endpoint: s3.us-east.cloud-object-storage.appdomain.cloud
  :arches:
  - src
  - noarch
  - ppc64le
  - s390x
  - x86_64
  :content:
    :21-uhlmann:
      :targets:
      - el10
      :rpms:
        :kafka: !ruby/regexp /.+-3\.7.+/
        :manageiq: !ruby/regexp /.+-21\.\d\.\d-(alpha|beta|rc)?\d+(\.\d)?\.el.+/
        :manageiq-release: !ruby/regexp /.+-21\.0.+/
        :python-pylxca: !ruby/regexp /.+-4\.2\.0.+/
        :repmgr13: !ruby/regexp /.+-5\.2\.1.+/
    :21-uhlmann-nightly:
      :targets:
      - el10
      :rpms:
        :manageiq-nightly: !ruby/regexp /.+-21\.\d\.\d-(\d\.\d\.)?\d{14,}+\.el.+/
