name: Build RPM Build container image
on:
  workflow_call:
permissions:
  contents: read
jobs:
  build_rpm_build_container:
    if: github.repository_owner == 'ManageIQ'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up registry credentials
      run: |
        echo "REGISTRY_USERNAME=${{ secrets.DOCKER_REGISTRY_USERNAME }}" >> $GITHUB_ENV
        echo "REGISTRY_PASSWORD=${{ secrets.DOCKER_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
    - name: Build and push RPM build image
      run: bin/build_container_image
